version: '3.8'

services:
  app:
    build:
      context: .
      target: dev # Default to development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - redis # Example of other services

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Add other services your team might need (DB, etc.)